#!/bin/bash -ex

HOSTNAME=subsonicapp
USERNAME=subsonic
GROUPNAME=subsonic

# set hostname
echo "$HOSTNAME" > /etc/hostname
sed -i "s|127.0.1.1 \(.*\)|127.0.1.1 $HOSTNAME|" /etc/hosts

# create the nzb userid (which all the nzb daemons run as)
groupadd $GROUPNAME
useradd -c "Application User" -d /home/$USERNAME -g $GROUPNAME -m -s /bin/bash "$USERNAME"
chown -R $USERNAME:$GROUPNAME /home/$USERNAME
# change subsonic to run as this user
sed -i "s|^SUBSONIC_USER=root|SUBSONIC_USER=$USERNAME|g" /etc/default/subsonic
# change the default subsonic arguments
# sed -i "s|^SUBSONIC_ARGS=\(.*\)|SUBSONIC_ARGS=\"--port=4040 --max-memory=150\"|" /etc/default/subsonic

# add the python installation tools and sudo
echo "deb http://www.deb-multimedia.org squeeze main non-free" >> /etc/apt/sources.list
apt-get update

DEBIAN_FRONTEND=noninteractive apt-get -y \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold \
    install python-software-properties sudo unrar-free openjdk-6-jre-headless smbfs 

DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold \
    install x264 lame ffmpeg



####################################################
# modify the transcode links
####################################################
cd /var/subsonic/transcode
rm ffmpeg
rm lame
ln -s /usr/local/bin/ffmpeg /var/subsonic/transcode/ffmpeg
ln -s /usr/local/bin/lame /var/subsonic/transcode/lame
ls

####################################################
# INSTALL lighttpd as a forwarder
####################################################
wget ftp://ftp.debian.org/debian/pool/main/l/lighttpd/lighttpd_1.4.31-1+b1_i386.deb
dpkg -i light* 

#DEBIAN_FRONTEND=noninteractive apt-get -y \
#    -o DPkg::Options::=--force-confdef \
#    -o DPkg::Options::=--force-confold \
#    install \
#    lighttpd

# stop the service now!
service lighttpd stop

####################################################
# Create the service file
####################################################
echo "Subsonic:       http://\$ipaddr:4040"  >  /etc/confconsole/services.txt
echo "Web Shell:      http://\$ipaddr:12320" >> /etc/confconsole/services.txt
echo "Webmin:         http://\$ipaddr:12321" >> /etc/confconsole/services.txt


####################################################
# done!
####################################################
exit




