#!/bin/bash -ex

####################################################
# install debs
####################################################
dpkg -i --force-confdef --force-confold /debs/*.deb
rm -rf /debs/*.deb



